// Copyright Ion Fusion contributors. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

package buildlogic

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import org.gradle.work.DisableCachingByDefault
import java.time.Instant
import java.time.temporal.ChronoUnit


/**
 * Generates a properties file that describes one of our artifacts so that
 * tools and consuming applications can introspect the jars on their classpath.
 *
 * Every artifact writes to the *same* resource path, prefixing its keys with its own
 * artifact id. A reader can then enumerate all copies of that path via
 * `ClassLoader.getResources()` and describe every artifact present, rather than
 * whichever one happens to win the classpath race. That also survives being repacked
 * into a shaded jar, where the several files are merged into one.
 */
@DisableCachingByDefault(because = "Writes six properties; caching would cost more than it saves")
abstract class GenerateJarInfo : DefaultTask()
{
    /** Identifies the artifact being described; prefixes every generated key. */
    @get:Input
    abstract val artifactId: Property<String>

    @get:Input
    abstract val artifactVersion: Property<String>

    @get:Input
    abstract val shortCommitHash: Property<String>

    @get:Input
    abstract val longCommitHash: Property<String>

    @get:Input
    abstract val commitDate: Property<String>

    @get:Input
    abstract val repoStatus: Property<String>

    /** Location of the generated file, relative to [outputDirectory]. */
    @get:Input
    abstract val resourcePath: Property<String>

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty


    @TaskAction
    fun generate()
    {
        val prefix = artifactId.get()

        // The build date is deliberately *not* a task input, so it records when this
        // metadata last changed rather than when the build last ran. Were it an input,
        // the task could never be up to date, and every build would rewrite a resource
        // and thus repack a jar that is otherwise unchanged.
        val buildDate = Instant.now().truncatedTo(ChronoUnit.SECONDS).toString()

        val entries = linkedMapOf(
            "$prefix.version"         to artifactVersion.get(),
            "$prefix.buildDate"       to buildDate,
            "$prefix.commitDate"      to commitDate.get(),
            "$prefix.shortCommitHash" to shortCommitHash.get(),
            "$prefix.longCommitHash"  to longCommitHash.get(),
            "$prefix.repoStatus"      to repoStatus.get()
        )

        val text = buildString {
            append("# Generated by the `buildlogic.jar-info-conventions` Gradle plugin.\n")
            append("# Do not edit; do not check in.\n")
            entries.forEach { (key, value) ->
                append(key).append('=').append(value).append('\n')
            }
        }

        val file = outputDirectory.file(resourcePath).get().asFile
        file.parentFile.mkdirs()
        // `Properties.load(InputStream)` decodes ISO-8859-1, so we encode to match.
        file.writeText(text, Charsets.ISO_8859_1)
    }
}
