# Copyright Ion Fusion contributors. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

IncludedModules = /fusion

# Excluded modules are relative to the included set.
# ExcludedModules = /fusion/private
