# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
    os: ubuntu-24.04

    # We don't need this, but RtD requires at least one tool.
    tools:
        python: "3.10"

    apt_packages:
        - openjdk-8-jdk-headless   # For our code
        - openjdk-17-jdk-headless  # For Gradle 9.x

    jobs:
        # This is just here to log the shell environment.
        post_system_dependencies:
            - env
            - which -a java
            - java --version
        build:
            html:
                - ./gradlew installDist
                - mkdir -p "${READTHEDOCS_OUTPUT}"
                - mv sdk/build/install/ion-fusion-sdk/docs "${READTHEDOCS_OUTPUT}/html"
