# Copyright Ion Fusion contributors. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Configuration for the Structural plugin.
# https://github.com/adrianczuczka/structural

# For each package, declare other packages it can depend on.
rules:

    # High-level structure; this breaks finer-grained rules below.
#    "dev.ionfusion.runtime":
#        - "dev.ionfusion.commons"
#        - "dev.ionfusion.commons.attributes"
#        - "dev.ionfusion.commons.resources"
#        - "dev.ionfusion.fusion"
#    "dev.ionfusion.fusion":
#        - "dev.ionfusion.commons"

    "dev.ionfusion.commons.resources":
        - "dev.ionfusion.commons.attributes"
        - "dev.ionfusion.runtime._private.util"

    "dev.ionfusion.fusion!":
#        - "dev.ionfusion.commons.**"                    # XXX Does not work
        - "dev.ionfusion.commons.attributes"
        - "dev.ionfusion.commons.resources"
        - "dev.ionfusion.runtime._private.cover"
        - "dev.ionfusion.runtime._private.doc"
        - "dev.ionfusion.runtime._private.util"
        - "dev.ionfusion.runtime.base"
        - "dev.ionfusion.runtime.embed"

    "dev.ionfusion.runtime._private.cover":
        - "dev.ionfusion.commons.resources"
        - "dev.ionfusion.runtime._private.util"
        - "dev.ionfusion.runtime.base"
        - "dev.ionfusion.runtime.embed"

    "dev.ionfusion.runtime._private.doc":
        - "dev.ionfusion.runtime._private.util"
        - "dev.ionfusion.runtime.base"
        - "dev.ionfusion.runtime.embed"

    "dev.ionfusion.runtime.base":
        - "dev.ionfusion.commons.attributes"
        - "dev.ionfusion.commons.resources"
        - "dev.ionfusion.runtime._private.util"

    "dev.ionfusion.runtime.embed":
        - "dev.ionfusion.commons.resources"
        - "dev.ionfusion.runtime.base"

# Declare class-import-class rules, generally for exceptions to the package rules above.
classAllowlist:
    "dev.ionfusion.**":
        - "dev.ionfusion.fusion._Private_*"
    "dev.ionfusion.runtime._private.util.IonCatalogLoader":
        - "dev.ionfusion.commons.resources"
