/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
    distribution
}

dependencies {
    implementation(project(":runtime"))

    testImplementation(project(":testing"))
    testImplementation("org.htmlunit:htmlunit:4.19.0")
}


// TODO There's probably a cleaner way to do this
val mainFusionRepo = layout.projectDirectory.dir("../runtime/src/main/fusion")


// This subproject currently doesn't have and Java code
tasks.jar {
    enabled = false
}

//=============================================================================
// Tests

tasks.test {
    // Install the tarball so we can test it.
    dependsOn(tasks.installDist)
}


//=============================================================================
// Application

// It took a loooong time to figure out how to access APP_HOME.
// https://discuss.gradle.org/t/42870/4
// https://stackoverflow.com/questions/22153041?rq=3
// It's still not entirely working: `gradle run` doesn't see the replaced script.
tasks.startScripts {
    doLast {
        unixScript.writeText(unixScript.readText().replace("{{APP_HOME}}", "'\${APP_HOME}'"))
        windowsScript.writeText(windowsScript.readText().replace("{{APP_HOME}}", "%APP_HOME%"))
    }
}

application {
    applicationName = "fusion"
    mainClass.set("dev.ionfusion.fusion.cli.Cli")
    // This is unused today, but is likely to be useful and it was hard to do.
    applicationDefaultJvmArgs = listOf("-Ddev.ionfusion.fusion.Home={{APP_HOME}}/fusion")
}


//=============================================================================
// Documentation

val fusiondoc = tasks.register<JavaExec>("fusiondoc") {
    group = "Documentation"
    description = "Generates Fusion language and library documentation."

    val fusiondocDir = layout.buildDirectory.dir("docs/fusiondoc")

    var docSrcDir   = layout.projectDirectory.dir("src/doc")
    var articlesDir = docSrcDir.dir("articles")
    var assetsDir   = docSrcDir.dir("assets")

    javaLauncher = javaToolchains.launcherFor {
        languageVersion = java.toolchain.languageVersion
    }

    classpath = sourceSets["main"].runtimeClasspath
    mainClass = "dev.ionfusion.fusion.cli.Cli"
    args = listOf("document",
                  "--modules",  mainFusionRepo.toString(),
                  "--articles", articlesDir.toString(),
                  "--assets",   assetsDir.toString(),
                  fusiondocDir.get().asFile.path)

    enableAssertions = true

    // Docgen has Java code! Not sure if this is the best solution...
    dependsOn(tasks.compileJava)

    inputs.dir(mainFusionRepo)
    inputs.dir(docSrcDir)
    outputs.dir(fusiondocDir)
}


//=============================================================================
// Distribution
// https://docs.gradle.org/current/userguide/application_plugin.html#sec:the_distribution


distributions {
    main {
        distributionBaseName = "ion-fusion-sdk"

        contents {
            val javadoc = project(":runtime").tasks.javadoc

            // TODO JavaDocs should be beside, not inside, the Fusion docs.
            //  https://github.com/ion-fusion/fusion-java/issues/204
            into("docs") {
                from(fusiondoc)
            }
            into("docs/javadoc") {
                from(javadoc)
            }
        }
    }
}


//=============================================================================
// Distribution

// Gradle doesn't seem to have an equivalent "do everything" task.
tasks.register("release") {
    group = "Build"
    description = "Build all artifacts and reports"

    dependsOn(tasks.assemble, tasks.check)
}
